safe: true
lsi: false
markdown:  redcarpet
permalink: pretty
pygments:  true
timezone: America/Los_Angeles
exclude: ["README.md","bower.json","package.json","LICENSE.md","node_modules","vendor","Gruntfile.js","Gemfile*","CNAME"]
